In [113]:
my_dict = {'key': 1, 'key_2': 22}

In [114]:
my_dict.keys()

dict_keys(['key', 'key_2'])

In [115]:
my_dict.keys()

dict_keys(['key', 'key_2'])

In [116]:
my_dict.values()

dict_values([1, 22])

In [117]:
my_dict["height"] = 1.8
print(my_dict)

{'key': 1, 'key_2': 22, 'height': 1.8}

In [118]:
print(my_dict)

{'key': 1, 'key_2': 22, 'height': 1.8}

**Make a copy**

In [119]:
my_dict.update({"height": 2})

In [120]:
print(my_dict.values())

dict_values([1, 22, 2])

In [121]:
my_dict_copy = my_dict.copy()

In [122]:
new_dict = my_dict_copy

In [123]:
print(new_dict)

{'key': 1, 'key_2': 22, 'height': 2}

In [124]:
my_dict.update({"height": 3})

In [125]:
print(my_dict)

{'key': 1, 'key_2': 22, 'height': 3}

**Remove element**

In [126]:
my_dict.pop("key")

1

In [127]:
print(my_dict.items())

dict_items([('key_2', 22), ('height', 3)])

In [128]:
print(my_dict)

{'key_2': 22, 'height': 3}

In [129]:
my_dict.clear()

In [130]:
print(my_dict)

{}

**If Statement**

In [131]:
countries = ['United State', 'India', 'China', 'Brazil' ]

In [132]:
for country in enumerate(countries):
    print(country)

(0, 'United State')
(1, 'India')
(2, 'China')
(3, 'Brazil')

In [133]:
print(country)

(3, 'Brazil')

In [134]:
my_data = {'name': 'Frank', 'age': 36}

In [135]:
for key, value in my_data.items():
    print(key)
    print(value)

name
Frank
age
36

In [136]:
len(countries)

4

In [137]:
max([10, 63, 81, 1, 99])

99

In [138]:
min([10, 63, 81, 1, 99])

1

In [139]:
type([10])

list

In [140]:
print(countries.index("China"))

2

**OS Module**

In [141]:
import os

In [142]:
os.getcwd()

'C:\\Users\\HP\\Documents\\Studio Venture\\ai-journey'

In [143]:
os.listdir()

['.idea',
 '.ipynb_checkpoints',
 '.learning-py.ipynb.layout',
 'learning-py.ipynb',
 'Untitled.ipynb',
 'Untitled1.ipynb']

In [144]:
# os.rmdir("new_folder")

In [145]:
os.listdir()

['.idea',
 '.ipynb_checkpoints',
 '.learning-py.ipynb.layout',
 'learning-py.ipynb',
 'Untitled.ipynb',
 'Untitled1.ipynb']

**Creating dataframe from an array**

In [146]:
import pandas as pd
import numpy as np

In [147]:
# Creating an array
arr = np.array([[1,4], [3, 6], [3, 6]])
print(arr * 2)

[[ 2  8]
 [ 6 12]
 [ 6 12]]

In [148]:
# Creating a dataframe
df = pd.DataFrame(arr, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])

In [149]:
df

      col1  col2
row1     1     4
row2     3     6
row3     3     6

***Option 2***

In [150]:
data = [[1,4], [3, 6], [3, 6]]

df = pd.DataFrame(data, columns=['cols1', 'cols2'], index=["rol1", "rol2", "rol3"])

In [151]:
df

      cols1  cols2
rol1      1      4
rol2      3      6
rol3      3      6

***Creating a Dataframe from a dictionary***

In [152]:
# List used for this example
states = ["California", "Texas", "Florida", "New York"]
population = [39903, 232323, 31113, 90009]

In [153]:
# Storing lists within a dictionary
dict_states = {"states": states, "Population": population}

In [154]:
print(dict_states)

{'states': ['California', 'Texas', 'Florida', 'New York'], 'Population': [39903, 232323, 31113, 90009]}

In [155]:
# Creating the dataframe
df_population = pd.DataFrame(dict_states)

In [156]:
df_population

       states  Population
0  California       39903
1       Texas      232323
2     Florida       31113
3    New York       90009

In [157]:
# Display n rows 
pd.set_option('display.max_rows', 1000)

In [158]:
# Precision 
# Set decimal precision
pd.set_option('display.precision', 2)

**Attributes and Methods**

In [159]:
# data types of each column
df_population.dtypes

states        object
Population     int64
dtype: object

In [160]:
# Getting the shape of the dataframe
df_population.shape

(4, 2)

In [161]:
df_population.columns

Index(['states', 'Population'], dtype='object')

In [162]:
# Showing info

df_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   states      4 non-null      object
 1   Population  4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [163]:
# Describe

In [164]:
df_population.describe()

       Population
count         4.0
mean      98337.0
std       93014.7
min       31113.0
25%       37705.5
50%       64956.0
75%      125587.5
max      232323.0

In [165]:
# Obtaining the length of the dataframe(row)
len(df_population)

4

In [166]:
# Obtaining the highest index of the dataframe
max(df_population.index)

3

In [167]:
min(df_population.index)

0

In [168]:
type(df_population)

pandas.core.frame.DataFrame

In [169]:
# Rounding the values of dataset
round(df_population, 2)

       states  Population
0  California       39903
1       Texas      232323
2     Florida       31113
3    New York       90009

***Selecting One Column***

*Syntax 1*

In [170]:
# Selecting a column with [] (prefered way to select column)
df_population["states"]

0    California
1         Texas
2       Florida
3      New York
Name: states, dtype: object

In [188]:
import pandas as pd
import numpy as np
# Show all rows
pd.set_option('display.max_rows', None)

# Show all columns
pd.set_option('display.max_columns', None)

# Do not truncate column width
pd.set_option('display.max_colwidth', None)

# Prevent line wrapping in the middle of columns
pd.set_option('display.expand_frame_repr', False)

In [172]:
# Showing the last 5 tail
df_population.head()

       states  Population
0  California       39903
1       Texas      232323
2     Florida       31113
3    New York       90009

In [173]:
# Showing the last 5 tail
df_population.tail()

       states  Population
0  California       39903
1       Texas      232323
2     Florida       31113
3    New York       90009

In [174]:
# Getting the last 2 rows
df_population.tail(2)

     states  Population
2   Florida       31113
3  New York       90009

In [175]:
# Getting the first 2 rows
df_population.head(2)

       states  Population
0  California       39903
1       Texas      232323

In [176]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['NYC', 'London', 'Paris']
})

In [177]:
df[["Name", "Age"]]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [178]:
df["Age in 5 years"] = df["Age"] +5

In [179]:
df

      Name  Age    City  Age in 5 years
0    Alice   25     NYC              30
1      Bob   30  London              35
2  Charlie   35   Paris              40

In [180]:
df["Score"] = [80, 90, 65]

In [181]:
df

      Name  Age    City  Age in 5 years  Score
0    Alice   25     NYC              30     80
1      Bob   30  London              35     90
2  Charlie   35   Paris              40     65

In [182]:
df["Status"] = "Active"

In [183]:
df

      Name  Age    City  Age in 5 years  Score  Status
0    Alice   25     NYC              30     80  Active
1      Bob   30  London              35     90  Active
2  Charlie   35   Paris              40     65  Active

In [190]:
df["Pass"] = df["Score"] >= 50

In [191]:
df["Result"] = np.where(df["Pass"], "Passed", "Failed")

In [192]:
df

      Name  Age    City  Age in 5 years  Score  Status  Pass  Result
0    Alice   25     NYC              30     80  Active  True  Passed
1      Bob   30  London              35     90  Active  True  Passed
2  Charlie   35   Paris              40     65  Active  True  Passed

In [155]:
df['Result(2)'] = df['Pass'].apply(lambda x: 'Passed' if x else 'Failed')

In [157]:
df

      Name  Age    City  Age in 5 years  Score  Status  Pass  Result Result(2)
0    Alice   25     NYC              30     80  Active  True  Passed    Passed
1      Bob   30  London              35     90  Active  True  Passed    Passed
2  Charlie   35   Paris              40     65  Active  True  Passed    Passed

In [193]:
import pandas as pd
import numpy as np

In [194]:
# Create an array of 1000 elements
new_arr = np.arange(0, 10000)

In [195]:
new_df= pd.DataFrame(new_arr)

In [196]:
new_df.head()

   0
0  0
1  1
2  2
3  3
4  4

In [197]:
pd.reset_option("display.max_rows")

In [198]:
new_df

         0
0        0
1        1
2        2
3        3
4        4
...    ...
9995  9995
9996  9996
9997  9997
9998  9998
9999  9999

[10000 rows x 1 columns]

In [201]:
df2 = pd.DataFrame({
    f'Col{i}': range(3) for i in range(1, 21)
})

In [200]:
df2

   Col1  Col2  Col3  Col4  Col5  Col6  Col7  Col8  Col9  Col10  Col11  Col12  Col13  Col14  Col15  Col16  Col17  Col18  Col19  Col20
0     0     0     0     0     0     0     0     0     0      0      0      0      0      0      0      0      0      0      0      0
1     1     1     1     1     1     1     1     1     1      1      1      1      1      1      1      1      1      1      1      1
2     2     2     2     2     2     2     2     2     2      2      2      2      2      2      2      2      2      2      2      2

In [199]:
int_lang = np.random.randint(1, 100, size=3)

In [231]:
df2["language_score"] = int_lang

In [46]:
df2

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12,Col13,Col14,Col15,Col16,Col17,Col18,Col19,Col20
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

In [237]:
min(int_lang)

32

In [202]:
random_float = np.random.uniform(1, 100, size=3)

***Creating a series using the random numbers***

In [204]:
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

***Creating series using the random numbers***

In [205]:
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [206]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: False]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table, or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: None]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: None]
display.max_dir_items : int
    The number of items that will be added to `dir(...)`. 'None' value means
    unlimited. Because dir is cached, changing this option will not immediately
    affect already existing dataframes until a column is deleted or added.

    This is for instance used to suggest columns from a dataframe to tab
    completion.
    [default: 100] [currently: 100]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]
display.max_seq_items : int or None
    When pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 2]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 80]
future.infer_string Whether to infer sequence of str objects as pyarrow string dtype, which will be the default in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
future.no_silent_downcasting Whether to opt-in to the future behavior which will *not* silently downcast results from Series and DataFrame `where`, `mask`, and `clip` methods. Silent downcasting will be removed in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
io.excel.ods.reader : string
    The default Excel reader engine for 'ods' files. Available options:
    auto, odf, calamine.
    [default: auto] [currently: auto]
io.excel.ods.writer : string
    The default Excel writer engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.xls.reader : string
    The default Excel reader engine for 'xls' files. Available options:
    auto, xlrd, calamine.
    [default: auto] [currently: auto]
io.excel.xlsb.reader : string
    The default Excel reader engine for 'xlsb' files. Available options:
    auto, pyxlsb, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.reader : string
    The default Excel reader engine for 'xlsm' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.writer : string
    The default Excel writer engine for 'xlsm' files. Available options:
    auto, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.reader : string
    The default Excel reader engine for 'xlsx' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsx.writer : string
    The default Excel writer engine for 'xlsx' files. Available options:
    auto, openpyxl, xlsxwriter.
    [default: auto] [currently: auto]
io.hdf.default_format : format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
    [default: None] [currently: None]
io.hdf.dropna_table : boolean
    drop ALL nan rows when appending to a table
    [default: False] [currently: False]
io.parquet.engine : string
    The default parquet reader/writer engine. Available options:
    'auto', 'pyarrow', 'fastparquet', the default is 'auto'
    [default: auto] [currently: auto]
io.sql.engine : string
    The default sql reader/writer engine. Available options:
    'auto', 'sqlalchemy', the default is 'auto'
    [default: auto] [currently: auto]
mode.chained_assignment : string
    Raise an exception, warn, or no action if trying to use chained assignment,
    The default is warn
    [default: warn] [currently: warn]
mode.copy_on_write : bool
    Use new copy-view behaviour using Copy-on-Write. Defaults to False,
    unless overridden by the 'PANDAS_COPY_ON_WRITE' environment variable
    (if set to "1" for True, needs to be set before pandas is imported).
    [default: False] [currently: False]
mode.data_manager : string
    Internal data manager type; can be "block" or "array". Defaults to "block",
    unless overridden by the 'PANDAS_DATA_MANAGER' environment variable (needs
    to be set before pandas is imported).
    [default: block] [currently: block]
    (Deprecated, use `` instead.)
mode.sim_interactive : boolean
    Whether to simulate interactive mode for purposes of testing
    [default: False] [currently: False]
mode.string_storage : string
    The default storage for StringDtype.
    [default: auto] [currently: auto]
mode.use_inf_as_na : boolean
    True means treat None, NaN, INF, -INF as NA (old way),
    False means None and NaN are null, but INF, -INF are not NA
    (new way).

    This option is deprecated in pandas 2.1.0 and will be removed in 3.0.
    [default: False] [currently: False]
    (Deprecated, use `` instead.)
plotting.backend : str
    The plotting backend to use. The default value is "matplotlib", the
    backend provided with pandas. Other backends can be specified by
    providing the name of the module that implements the backend.
    [default: matplotlib] [currently: matplotlib]
plotting.matplotlib.register_converters : bool or 'auto'.
    Whether to register converters with matplotlib's units registry for
    dates, times, datetimes, and Periods. Toggling to False will remove
    the converters, restoring any converters that pandas overwrote.
    [default: auto] [currently: auto]
styler.format.decimal : str
    The character representation for the decimal separator for floats and complex.
    [default: .] [currently: .]
styler.format.escape : str, optional
    Whether to escape certain characters according to the given context; html or latex.
    [default: None] [currently: None]
styler.format.formatter : str, callable, dict, optional
    A formatter object to be used as default within ``Styler.format``.
    [default: None] [currently: None]
styler.format.na_rep : str, optional
    The string representation for values identified as missing.
    [default: None] [currently: None]
styler.format.precision : int
    The precision for floats and complex numbers.
    [default: 6] [currently: 6]
styler.format.thousands : str, optional
    The character representation for thousands separator for floats, int and complex.
    [default: None] [currently: None]
styler.html.mathjax : bool
    If False will render special CSS classes to table attributes that indicate Mathjax
    will not be used in Jupyter Notebook.
    [default: True] [currently: True]
styler.latex.environment : str
    The environment to replace ``\begin{table}``. If "longtable" is used results
    in a specific longtable environment format.
    [default: None] [currently: None]
styler.latex.hrules : bool
    Whether to add horizontal rules on top and bottom and below the headers.
    [default: False] [currently: False]
styler.latex.multicol_align : {"r", "c", "l", "naive-l", "naive-r"}
    The specifier for horizontal alignment of sparsified LaTeX multicolumns. Pipe
    decorators can also be added to non-naive values to draw vertical
    rules, e.g. "\|r" will draw a rule on the left side of right aligned merged cells.
    [default: r] [currently: r]
styler.latex.multirow_align : {"c", "t", "b"}
    The specifier for vertical alignment of sparsified LaTeX multirows.
    [default: c] [currently: c]
styler.render.encoding : str
    The encoding used for output HTML and LaTeX files.
    [default: utf-8] [currently: utf-8]
styler.render.max_columns : int, optional
    The maximum number of columns that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.max_elements : int
    The maximum number of data-cell (<td>) elements that will be rendered before
    trimming will occur over columns, rows or both if needed.
    [default: 262144] [currently: 262144]
styler.render.max_rows : int, optional
    The maximum number of rows that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.repr : str
    Determine which output to use in Jupyter Notebook in {"html", "latex"}.
    [default: html] [currently: html]
styler.sparse.columns : bool
    Whether to sparsify the display of hierarchical columns. Setting to False will
    display each explicit level element in a hierarchical key for each column.
    [default: True] [currently: True]
styler.sparse.index : bool
    Whether to sparsify the display of a hierarchical index. Setting to False will
    display each explicit level element in a hierarchical key for each row.
    [default: True] [currently: True]

In [65]:
series1.describe()

count    1000.000000
mean       51.998000
std        28.162619
min         1.000000
25%        27.000000
50%        53.000000
75%        76.000000
max        99.000000
dtype: float64

In [207]:
df_new = pd.DataFrame({})

In [210]:
df_new = df_new.assign(score1=series1, score2=series2)

In [209]:
df_new

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1000 rows x 0 columns]

Adding a content using the insert()

In [211]:
df_new.insert(1, 'test', series1)

In [77]:
df_new

     score1  test  score2
0        89    89      75
1        76    76      66
2        53    53      72
3        77    77      61
4        19    19      55
..      ...   ...     ...
995      51    51      94
996      32    32      17
997      13    13      44
998      55    55      14
999      42    42      68

[1000 rows x 3 columns]

Math Operations

In [212]:
# Select a column and calculate total sum
total = df_new["score1"].sum() + df_new["score2"].sum()
print(total)

100421

# Count, mean, std, max and min

In [213]:
# Count, mean, std, max and min
total = df_new[["score1" ,"score2"]].count()
# print(total)
mean = df_new["score1"].mean()
# print(mean)
std = df_new["score1"].std()
# print(std)
max_value = df_new["score2"].max()
# print(max_value)
min_value = df_new["score2"].min()
# print(min_value)

# Operating in rows

In [217]:
# Calculating the sum in a row
df_new["Total"] =  df_new.sum(axis=1)
df_new

     score1  test  score2  Total
0        18    18      27    252
1        82    82      82    984
2        64    64      40    672
3         4     4      52    240
4        76    76      65    868
..      ...   ...     ...    ...
995      45    45      50    560
996      58    58      57    692
997      42    42      22    424
998      23    23      11    228
999      51    51      16    472

[1000 rows x 4 columns]

In [221]:
df_new = df_new.round(2)
df_new

     score1  test  score2  Total
0        18    18      27    252
1        82    82      82    984
2        64    64      40    672
3         4     4      52    240
4        76    76      65    868
..      ...   ...     ...    ...
995      45    45      50    560
996      58    58      57    692
997      42    42      22    424
998      23    23      11    228
999      51    51      16    472

[1000 rows x 4 columns]

## Value counts

In [227]:
# Counting element
# len function
len(df_new["score2"])
# Using the count
df_new["score2"].count()

np.int64(1000)

In [233]:
df_new["score2"].value_counts()

score2
65    18
57    18
71    18
60    17
77    16
      ..
38     5
41     5
25     4
2      4
69     3
Name: count, Length: 99, dtype: int64

In [234]:
# Return the relative frequency (divide all values by sum of the values)
df_new["score2"].value_counts(normalize=True)

score2
65    1.80e-02
57    1.80e-02
71    1.80e-02
60    1.70e-02
77    1.60e-02
        ...
38    5.00e-03
41    5.00e-03
25    4.00e-03
2     4.00e-03
69    3.00e-03
Name: proportion, Length: 99, dtype: float64

In [237]:
# converting the frequency to percentage
df_new["score1"].value_counts(normalize=True) * 100

for col in df_new.columns:
    print(f'Relative frequency for {col}')
    print(df_new[col].value_counts(normalize=True))

Relative frequency for score1
score1
3     1.50e-02
27    1.50e-02
4     1.50e-02
20    1.50e-02
67    1.40e-02
        ...
55    6.00e-03
92    5.00e-03
68    5.00e-03
62    4.00e-03
46    3.00e-03
Name: proportion, Length: 99, dtype: float64
Relative frequency for test
test
3     1.50e-02
27    1.50e-02
4     1.50e-02
20    1.50e-02
67    1.40e-02
        ...
55    6.00e-03
92    5.00e-03
68    5.00e-03
62    4.00e-03
46    3.00e-03
Name: proportion, Length: 99, dtype: float64
Relative frequency for score2
score2
65    1.80e-02
57    1.80e-02
71    1.80e-02
60    1.70e-02
77    1.60e-02
        ...
38    5.00e-03
41    5.00e-03
25    4.00e-03
2     4.00e-03
69    3.00e-03
Name: proportion, Length: 99, dtype: float64
Relative frequency for Total
Total
532     1.00e-02
524     1.00e-02
832     1.00e-02
612     9.00e-03
596     9.00e-03
          ...
1152    1.00e-03
608     1.00e-03
188     1.00e-03
92      1.00e-03
128     1.00e-03
Name: proportion, Length: 253, dtype: float64

In [251]:
# Counting by category
seriesCategory = pd.Series(np.random.randint(0, 100, size=1000))
df_new['Category'] = seriesCategory

counts = df_new["Category"].value_counts()
counts_cat = df_new.groupby("score1")["Category"].size()
counts_cat

score1
1      6
2     10
3     15
4     15
5     11
      ..
95    14
96    13
97     6
98    10
99    13
Name: Category, Length: 99, dtype: int64