# Sorting in DataFrame

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Score": [60, 20, 90, 87]
})

      Name  Score
0    Alice     60
1      Bob     20
2  Charlie     90
3    David     87

In [6]:
# Sort by score ascending
df_sort_ascend = df.sort_values(by="Score", ascending=True)
df_sort_ascend

      Name  Score
1      Bob     20
0    Alice     60
3    David     87
2  Charlie     90

In [7]:
# Sort by score descending
df_sort_descend = df.sort_values(by="Score", ascending=False)
df_sort_descend

      Name  Score
2  Charlie     90
3    David     87
0    Alice     60
1      Bob     20

In [8]:
# Sort by Multiple columns
df.sort_values(by=["Score", "Name"], ascending=[True, False])

      Name  Score
1      Bob     20
0    Alice     60
3    David     87
2  Charlie     90

Sort DataFrame by index

In [9]:
df.sort_index(ascending=[True, False])

      Name  Score
0    Alice     60
1      Bob     20
2  Charlie     90
3    David     87

Sort Series

In [15]:
s = pd.Series(["Alice", "Bob", "Charlie", "David"])
sorted_series = s.sort_values(ascending=False)
print(sorted_series)

# Using the in

3      David
2    Charlie
1        Bob
0      Alice
dtype: object

### Using the inplace=True directly modifies the series or dataframe without returning new object

In [21]:
# Sorting by key functions
sort_key_func = df.sort_values(by="Score", ascending=True, key=lambda x: x.astype(float))

print(sort_key_func)

      Name  Score
1      Bob     20
0    Alice     60
3    David     87
2  Charlie     90

## Creating and modifying index

In [25]:
df.set_index("Name", inplace=True)

KeyError: "None of ['Name'] are in the columns"

In [34]:
df.reset_index()

        ID  Score
0    Alice     60
1      Bob     20
2  Charlie     90
3    David     87

# Renaming Columns and Index

In [35]:
# using .rename()
df.rename()